insert into Models (name) values ('Elantra');
insert into Models (name) values ('7 Series');
insert into Models (name) values ('Accord');
insert into Models (name) values ('Land Cruiser');
insert into Models (name) values ('SL-Class');
insert into Models (name) values ('Sorento');
insert into Models (name) values ('E-Series');
insert into Models (name) values ('S10');
insert into Models (name) values ('Mariner');
insert into Models (name) values ('Caravan');
insert into Models (name) values ('Safari');
insert into Models (name) values ('Solara');
insert into Models (name) values ('Impreza');
insert into Models (name) values ('Rabbit');
insert into Models (name) values ('Thunderbird');
insert into Models (name) values ('Avalanche');
insert into Models (name) values ('Sierra 2500');
insert into Models (name) values ('Aries');
insert into Models (name) values ('Aerostar');
insert into Models (name) values ('Quest');
insert into Models (name) values ('Landaulet');
insert into Models (name) values ('Echo');
insert into Models (name) values ('Eos');
insert into Models (name) values ('Grand Marquis');
insert into Models (name) values ('Explorer');
insert into Models (name) values ('Miata MX-5');
insert into Models (name) values ('Z4');
insert into Models (name) values ('Azera');
insert into Models (name) values ('CLK-Class');
insert into Models (name) values ('Silverado');
insert into Models (name) values ('Camaro');
insert into Models (name) values ('Club Wagon');
insert into Models (name) values ('LeSabre');
insert into Models (name) values ('924');
insert into Models (name) values ('Karif');
insert into Models (name) values ('Justy');
insert into Models (name) values ('600SEL');
insert into Models (name) values ('M3');
insert into Models (name) values ('I');
insert into Models (name) values ('Prius');
insert into Models (name) values ('7 Series');
insert into Models (name) values ('X5 M');
insert into Models (name) values ('S10');
insert into Models (name) values ('Starion');
insert into Models (name) values ('Liberty');
insert into Models (name) values ('Esprit');
insert into Models (name) values ('RX Hybrid');
insert into Models (name) values ('300E');
insert into Models (name) values ('CLK-Class');
insert into Models (name) values ('Tracer');
