"""deleted created at column in orders

Revision ID: 02349e8d70a4
Revises: 09fc79e941f8
Create Date: 2026-04-10 22:16:26.418937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02349e8d70a4'
down_revision = '09fc79e941f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema='lyfter_ecommerce') as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema='lyfter_ecommerce') as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
