"""add order number column to orders

Revision ID: 0274d5b48d88
Revises: 02349e8d70a4
Create Date: 2026-04-14 09:15:07.668251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0274d5b48d88'
down_revision = '02349e8d70a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema='lyfter_ecommerce') as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['order_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema='lyfter_ecommerce') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
