"""added columns to products orders table

Revision ID: 09fc79e941f8
Revises: 42776972fd65
Create Date: 2026-04-10 21:48:34.054852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fc79e941f8'
down_revision = '42776972fd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products_refunds', schema='lyfter_ecommerce') as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total_refunded', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Products_refunds', schema='lyfter_ecommerce') as batch_op:
        batch_op.drop_column('total_refunded')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
