"""added refunds, refundstypes and refundsproducts tables to db

Revision ID: 42776972fd65
Revises: 68d654237c84
Create Date: 2026-04-09 15:19:49.890889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42776972fd65'
down_revision = '68d654237c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Refunds_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('type_id', sa.Integer(), server_default='1', nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['lyfter_ecommerce.Orders.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['lyfter_ecommerce.Refunds_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Products_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('refund_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['lyfter_ecommerce.Products.id'], ),
    sa.ForeignKeyConstraint(['refund_id'], ['lyfter_ecommerce.Refunds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    with op.batch_alter_table('Orders', schema='lyfter_ecommerce') as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               server_default='1',
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema='lyfter_ecommerce') as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)

    op.drop_table('Products_refunds', schema='lyfter_ecommerce')
    op.drop_table('Refunds', schema='lyfter_ecommerce')
    op.drop_table('Refunds_types', schema='lyfter_ecommerce')
    # ### end Alembic commands ###
