"""Initial migration

Revision ID: 5bf9e2dd6b51
Revises: 
Create Date: 2026-03-24 11:17:25.066941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf9e2dd6b51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Carts_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Orders_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['lyfter_ecommerce.Carts_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['lyfter_ecommerce.Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['lyfter_ecommerce.Roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['lyfter_ecommerce.Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['lyfter_ecommerce.Carts.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['lyfter_ecommerce.Payment_methods.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['lyfter_ecommerce.Orders_status.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['lyfter_ecommerce.Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Products_carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['lyfter_ecommerce.Carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['lyfter_ecommerce.Products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Products_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_purchase', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['lyfter_ecommerce.Orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['lyfter_ecommerce.Products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Products_orders', schema='lyfter_ecommerce')
    op.drop_table('Products_carts', schema='lyfter_ecommerce')
    op.drop_table('Orders', schema='lyfter_ecommerce')
    op.drop_table('Users_roles', schema='lyfter_ecommerce')
    op.drop_table('Carts', schema='lyfter_ecommerce')
    op.drop_table('Users', schema='lyfter_ecommerce')
    op.drop_table('Roles', schema='lyfter_ecommerce')
    op.drop_table('Products', schema='lyfter_ecommerce')
    op.drop_table('Payment_methods', schema='lyfter_ecommerce')
    op.drop_table('Orders_status', schema='lyfter_ecommerce')
    op.drop_table('Carts_status', schema='lyfter_ecommerce')
    # ### end Alembic commands ###
