"""add default value to role in users roles

Revision ID: 68d654237c84
Revises: e73fd4560d4b
Create Date: 2026-04-09 11:56:41.801865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d654237c84'
down_revision = 'e73fd4560d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users_roles', schema='lyfter_ecommerce') as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               server_default='2',
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users_roles', schema='lyfter_ecommerce') as batch_op:
        batch_op.alter_column('role_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)

    # ### end Alembic commands ###
