"""added fullnamel, address and phone to orders table

Revision ID: 7236e78bbcfd
Revises: 12fc366c02ed
Create Date: 2026-09-10 20:52:41.983709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7236e78bbcfd'
down_revision = '12fc366c02ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema='lyfter_ecommerce') as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), server_default='Unknouwn', nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=500), server_default='N/A', nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), server_default='00000000', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema='lyfter_ecommerce') as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
