"""Add tokenblocklist table

Revision ID: bf6c6cbd47b1
Revises: d232db96622f
Create Date: 2026-05-08 13:32:27.767479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6c6cbd47b1'
down_revision = 'd232db96622f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Token_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    op.create_table('Token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['lyfter_ecommerce.Token_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['lyfter_ecommerce.Users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='lyfter_ecommerce'
    )
    with op.batch_alter_table('Token_blocklist', schema='lyfter_ecommerce') as batch_op:
        batch_op.create_index(batch_op.f('ix_lyfter_ecommerce_Token_blocklist_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Token_blocklist', schema='lyfter_ecommerce') as batch_op:
        batch_op.drop_index(batch_op.f('ix_lyfter_ecommerce_Token_blocklist_jti'))

    op.drop_table('Token_blocklist', schema='lyfter_ecommerce')
    op.drop_table('Token_type', schema='lyfter_ecommerce')
    # ### end Alembic commands ###
