"""added user id column to refunds and relationships

Revision ID: d232db96622f
Revises: 0274d5b48d88
Create Date: 2026-04-14 18:26:05.151257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd232db96622f'
down_revision = '0274d5b48d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Refunds', schema='lyfter_ecommerce') as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Users', ['user_id'], ['id'], referent_schema='lyfter_ecommerce')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Refunds', schema='lyfter_ecommerce') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
