"""add default value to status id in carts table/

Revision ID: e73fd4560d4b
Revises: 5bf9e2dd6b51
Create Date: 2026-04-06 12:29:34.790412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73fd4560d4b'
down_revision = '5bf9e2dd6b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carts', schema='lyfter_ecommerce') as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               server_default='1',
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Carts', schema='lyfter_ecommerce') as batch_op:
        batch_op.alter_column('status_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)

    # ### end Alembic commands ###
